### ISSUE TITLE
Pull out sealing exchange functionality from the trusted compute codebase into the wallet codebase

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/nautilus-wallet#1]
PRs:

- [x] #48
- [x] #67 

Follow-up issues:

- #88

## Tasks

 - [x] Remote attestation:
   - App gets and verifies attestation with the Enclave
   - Obtains enclave's public key

 - [x] Sealed enclave communication APIs:

   - Sealed request ("half-sealed"): 
     - Request message sealed to enclave's attested public key
     - Response message is not sealed

   - Sealed exchange ("fully-sealed"):
     - Client generates ephemeral keypair for exchange
     - Request message sealed to enclave's attested public key
     - Request sent along with client's ephemeral public key
     - Response message sealed to client's ephemeral public

 - Implementation notes:

   - On app side, these should be common JS helper functions

   - On server side, each of the above should probably correspond to
     a separate REST API endpoint and ECALL.

   - The message formats should probably all be JSON, for ease of implementation

   - For the fully-sealed exchange responses, we'll need variable-sized ECALL
     results. Since these should be mostly small, we can probably use the
     over-allocated out buffer approach? (Otherwise, OCALL or another strategy?)

**Comment by PiDelport** [comment]
@longtomjr: Should we keep DCAP attestation as part of this, or split it to a follow-up task?

**Comment by longtomjr** [comment]
@PiDelport I think splitting out a new issue would be better.

**Comment by PiDelport** [comment]
Cool, I split out:

- #88
