### ISSUE TITLE
Pull out offline transaction and account creation from algonaut into wallet-usable codebase

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/nautilus-wallet#2]
The goal here is to take the functionality that we need from [Algonaut](https://github.com/manuelmauro/algonaut) into a codebase that is either no-std compatible, or only use the Teaclave rust sdk's std library (with no-std being preferred if possible).

The functionality that we need is:
  - [x] Create account ([api docs](https://docs.rs/algonaut_transaction/0.2.0/algonaut_transaction/account/struct.Account.html)|[source](https://github.com/manuelmauro/algonaut/blob/main/algonaut_transaction/src/account.rs))
  - [x] Create and sign a transaction (several steps) { note: initially just try and implement it using the types, we can do the builders in the future if needed }
    - [x] Create the payment ([api docs](https://docs.rs/algonaut_transaction/0.2.0/algonaut_transaction/transaction/struct.Payment.html)|[source](https://github.com/manuelmauro/algonaut/blob/main/algonaut_transaction/src/transaction.rs))
    - [x] Create Transaction - for now we only need ["payment"](https://docs.rs/algonaut_transaction/0.2.0/algonaut_transaction/transaction/enum.TransactionType.html) transaction types. ([api docs](https://docs.rs/algonaut_transaction/0.2.0/algonaut_transaction/transaction/struct.Transaction.html)|[source](https://github.com/manuelmauro/algonaut/blob/main/algonaut_transaction/src/transaction.rs)) 
    - [x] Sign transaction using the sender's account ([api docs](https://docs.rs/algonaut_transaction/0.2.0/algonaut_transaction/account/struct.Account.html#method.sign_transaction)|[source](https://github.com/manuelmauro/algonaut/blob/main/algonaut_transaction/src/account.rs))

----

Repo: https://github.com/registreerocks/algonaut-sgx

**Comment by PiDelport** [comment]
We pulled this into an SGX-forked crate: https://github.com/registreerocks/algonaut-sgx
