### ISSUE TITLE
Create wallet functionality

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/nautilus-wallet#25]
## Web Client

 - Update "Create Wallet" view
   - [x] Add wallet creation form requesting name and pin - confirm pin.
   - [x] Send the details using a sealed api exchange - Depends on: #1
   - [x] Receive the sealed exchange result that contains the new Wallet ID (Algorand address)
   - [x] Prompt the user to save their wallet ID (provide QR-Code that can be printed)
   - [x] Redirect the user to the landing page.

PRs:
- [x] #59
- [x] #39 
- [x] #54 

## Web Server
 - [x] Add ~`/wallet` put~ `/wallet-operation` POST endpoint that takes a sealed payload for wallet creation and passes it to the enclave
 - [x] Unseal the payload inside of the enclave using the sealed api exchange functionality
 - [x] Add wallet creation functionality inside of the enclave using the ported Algonaut functionality
 - [x] Persist algorand account details alongside the pin using the KvStore - Depends on: #4
 - [x] Create a sealed api result containing the wallet ID (algorand address)

PRs:

- [x] #68

**Comment by PiDelport** [comment]
Wrapping this up for now: we can split out any trailing tasks.
