### ISSUE TITLE
Open wallet functionality

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/nautilus-wallet#26]
## Web Client

 - [x] UI: Wallet owner enters Wallet ID (or scan QR code) and PIN
 - Sealed API exchange:
   - [x] Request: Wallet open request, with access credentials
   - Response:
     - [x] Success: Nautilus Wallet ID, owner name, any other wallet details
     - [x] Failure: Bad PIN / Wallet ID
 - [x] UI: Show open wallet view, with owner details and balance

PRs:
- [x] #59

## Web Server
 - Sealed enclave exchange:
   - [x] Request: Wallet open request with access credentials
   - [x] Enclave Operation: Verify the access credentials, and return wallet details
   - Response:
     - [x] Success: Nautilus Wallet ID, owner name, any other wallet details
     - [x] Failure: Bad PIN / Wallet ID

Deferred to client:

- [x] Obtain account balance from Algorand node
 
PRs:

- [x] #68

**Comment by PiDelport** [comment]
Wrapping this up for now: we can split out any trailing tasks.
