### ISSUE TITLE
Transaction functionality

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/nautilus-wallet#27]
## Web Client

 - [x] Sender signs into their wallet using their PIN
 - [x] Receiver provides their Algorand address (As text or QR code) and inputs it into the app
 - Sealed API Request:
   - [x] App sends the Sender's Wallet ID and pin, alongside the Receiver's Address
   - [x] API returns Outcome result (Success/Failure with reasons?)

PRs:
- [x]  #59

## Web Server
 - Sealed enclave request: 
   - [x] Request: Transaction request, with Sending Wallet ID, Sending wallet PIN,
     and recieving wallet address
   - Enclave operation:
     - [x] Verify sending wallet ID + PIN and get the Wallet's private key
     - [x] Create offline transaction (using algo libary) using the sender and reciever's details
   - [x] Return the created transaction

Deferred to client:

 - [x] Submit and verify transaction to Algorand node

PRs:

- [x] #68

**Comment by PiDelport** [comment]
Wrapping this up for now: we can split out any trailing tasks.
