### ISSUE TITLE
Create frontend codebase scaffolding

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/nautilus-wallet#3]
- [x] Create Angular project - #7
 - [x] #9
 - [x] Use mobile 1st component library 
 - [x] Setup Storybook - #8
 - [x] Add empty pages for the views - #15 

> Empty views to setup:
> Landing page:
>  - Choose action: Create Wallet, Open Wallet
> 
> Create Wallet:
>  - Take creation details
>  - Show result and/or redirect to Opened Wallet
> 
> Open Wallet:
>  - Take wallet details
>  - Show errors, or redirect to Opened Wallet
> 
> Opened Wallet:
>  - Show wallet details (name, balance)
>  - Actions: Show QR code (for receiving), Send Funds
> 
> Send Funds:
>  - Take recipient details (from text field or scanning QR code)
>  - Show success / failure
>  - Refresh balance (?)
>  - Next: Opened Wallet

**Comment by PiDelport** [comment]
This should be done with #15. 🎉
